plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
	id 'java'
	id("me.modmuss50.mod-publish-plugin") version "0.8.1"
	id 'com.bouncingelf10.minecraft-version-compatibility-checker' version '1.7.0'
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	// Add repositories to retrieve artifacts from in here.
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()
	withJavadocJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

publishMods {
	file = tasks.jar.archiveFile
	additionalFiles.from(tasks.sourcesJar.archiveFile)
	additionalFiles.from(tasks.javadocJar.archiveFile)

	changelog = "2.0.0: API Consistency and bugfixes"
	type = STABLE
	modLoaders.add("fabric")

	modrinth {
		projectId = "vKDSSPpv"
		accessToken = providers.environmentVariable("MODRINTH_TOKEN")
		minecraftVersions.add("26.1")
		minecraftVersions.add("26.1.1")
		minecraftVersions.add("26.1.2")
	}

	curseforge {
		projectId = "1490074"
		accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
		minecraftVersions.add("26.1")
		minecraftVersions.add("26.1.1")
		minecraftVersions.add("26.1.2")
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
}